"""Shell completion 生成器。"""

from __future__ import annotations

import ast
import pathlib


def bin_dir() -> pathlib.Path:
    return pathlib.Path(__file__).resolve().parent.parent / "bin"


def tool_names(path: pathlib.Path | None = None) -> list[str]:
    path = path or bin_dir()
    return sorted(
        p.name for p in path.iterdir()
        if not p.name.startswith(".") and (p.is_file() or p.is_symlink())
    )


def subcommands(script: pathlib.Path) -> list[str]:
    try:
        tree = ast.parse(script.read_text(encoding="utf-8"))
    except (OSError, SyntaxError, UnicodeDecodeError):
        return []
    names: set[str] = set()
    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        is_cli = node.name.endswith("Cli") or node.name.endswith("CLI")
        for item in node.body:
            if isinstance(item, ast.FunctionDef) and not item.name.startswith("_"):
                names.add(item.name.replace("_", "-"))
                if "_" in item.name:
                    names.add(item.name)
            elif is_cli and isinstance(item, ast.FunctionDef) and item.name == "__init__":
                for init_node in ast.walk(item):
                    if not isinstance(init_node, ast.Assign):
                        continue
                    for target in init_node.targets:
                        if isinstance(target, ast.Attribute) and isinstance(target.value, ast.Name) and target.value.id == "self" and not target.attr.startswith("_"):
                            names.add(target.attr.replace("_", "-"))
                            if "_" in target.attr:
                                names.add(target.attr)
    names.discard("__call__")
    return sorted(names)


def completion_map(path: pathlib.Path | None = None) -> dict[str, list[str]]:
    path = path or bin_dir()
    result: dict[str, list[str]] = {}
    for name in tool_names(path):
        target = (path / name).resolve()
        result[name] = subcommands(target)
    return result


def _words(items: list[str]) -> str:
    return " ".join(items)


def bash_zsh_completion(data: dict[str, list[str]]) -> str:
    tools = _words(sorted(data))
    cases = "\n".join(
        f"    {name}) opts='{_words(commands)}' ;;"
        for name, commands in sorted(data.items())
        if commands
    )
    return f"""# Generated by lazygophers scripts inject. Do not edit.
if [ -n "${{ZSH_VERSION:-}}" ]; then
  autoload -Uz bashcompinit 2>/dev/null && bashcompinit 2>/dev/null
fi

_lazygophers_scripts_complete() {{
  local cur prev cmd opts
  cur="${{COMP_WORDS[COMP_CWORD]}}"
  prev="${{COMP_WORDS[COMP_CWORD-1]}}"
  cmd="${{COMP_WORDS[0]##*/}}"
  opts=""
  if [ "$COMP_CWORD" -eq 1 ]; then
    case "$cmd" in
{cases}
    esac
  fi
  COMPREPLY=( $(compgen -W "$opts --help --debug --dry-run --no-say" -- "$cur") )
}}
for _lazygophers_tool in {tools}; do
  complete -F _lazygophers_scripts_complete "$_lazygophers_tool" 2>/dev/null || true
done
unset _lazygophers_tool
"""


def fish_completion_for(tool: str, commands: list[str]) -> str:
    lines = ["# Generated by lazygophers scripts inject. Do not edit."]
    for option in ("help", "debug", "dry-run", "no-say"):
        lines.append(f"complete -c {tool} -l {option}")
    for command in commands:
        lines.append(f"complete -c {tool} -f -a {command}")
    return "\n".join(lines) + "\n"


def fish_completion(data: dict[str, list[str]]) -> str:
    return "".join(fish_completion_for(tool, commands) for tool, commands in sorted(data.items()))
